openapi: 3.1.0
info:
  title: Chat Storage
  description: Storing and managing chat messages exchanged with ChatGPT.
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /messages/{conversation_id}:
    post:
      operationId: addMessage
      summary: Add a message to the storage
      parameters:
      - in: path
        name: conversation_id
        schema:
          type: string
        required: true
        description: The ID of the conversation.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addMessageRequest'
      responses:
        '200':
          description: OK
    get:
      operationId: getMessages
      summary: Get messages from the storage
      parameters:
      - in: path
        name: conversation_id
        schema:
          type: string
        required: true
        description: The ID of the conversation.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getMessagesResponse'

components:
  schemas:
    addMessageRequest:
      type: object
      required:
        - message
        - tags
      properties:
        message:
          type: string
          description: The message that will be stored.
        tags:
          type: array
          items:
            type: string
          description: The tags associated with the message which are words that chatgpt deems relevant to enable more efficient searching.
    getMessagesResponse:
      type: array
      items:
        type: string
      description: The message.
