openapi: 3.1.0
info:
  title: Chat Storage
  description: Storing and managing chat messages exchanged with ChatGPT.
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /messages/{user_id}:
    post:
      operationId: addMessage
      summary: Add a message to the storage
      parameters:
      - in: path
        name: user_id
        schema:
          type: string
        required: true
        description: The ID of the user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addMessageRequest'
      responses:
        '200':
          description: OK
    get:
      operationId: getMessages
      summary: Get messages from the storage
      parameters:
      - in: path
        name: user_id
        schema:
          type: string
        required: true
        description: The ID of the user.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getMessagesResponse'

components:
  schemas:
    addMessageRequest:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: The message to add to the storage.
    getMessagesResponse:
      type: array
      items:
        type: string
      description: The list of messages.
